"""tablas pendientes

Revision ID: 75dac5226a93
Revises: a93ee5548d82
Create Date: 2025-08-05 22:44:51.809227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75dac5226a93'
down_revision: Union[str, Sequence[str], None] = 'a93ee5548d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acciones_pendientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('accion', sa.String(), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('mensaje_original', sa.String(), nullable=True),
    sa.Column('estado', sa.Enum('pendiente_confirmacion', 'confirmada', 'cancelada', 'ejecutada', 'error', name='estadoaccion'), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_confirmacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acciones_pendientes_id'), 'acciones_pendientes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_acciones_pendientes_id'), table_name='acciones_pendientes')
    op.drop_table('acciones_pendientes')
    # ### end Alembic commands ###
